/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chendongqi_me_memfilltool_MemOpUtils */

#ifndef _Included_chendongqi_me_memfilltool_MemOpUtils
#define _Included_chendongqi_me_memfilltool_MemOpUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chendongqi_me_memfilltool_MemOpUtils
 * Method:    memfill
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_chendongqi_me_memfilltool_MemOpUtils_memfill
  (JNIEnv *, jclass);

/*
 * Class:     chendongqi_me_memfilltool_MemOpUtils
 * Method:    memfree
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_chendongqi_me_memfilltool_MemOpUtils_memfree
  (JNIEnv *, jclass);

/*
 * Class:     chendongqi_me_memfilltool_MemOpUtils
 * Method:    setflag
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_chendongqi_me_memfilltool_MemOpUtils_setflag
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
